feat: customizable hop height for vires/polsvoice
ZQuestClassic/ZQuestClassic pull request #1043
Opened 2024-12-08 04:14 UTC by Jambu2024

2024-12-09 00:24 UTC, EmilyV99 commented on src/zc/guys.cpp
> +	if ((dmisc10 <= 0 || replay_version_check(0, 37)))
What if someone used dmisc10 in an old quest? It might not be <= 0, and then that old quest would break due to having the wrong values here- AND we wouldn't catch that bug with a replay due to the replay check...

Unsure on if this is ok as-is or not. I'll defer to @connorjclark on this.

2024-12-09 01:52 UTC, Jambu2024 commented on src/zc/guys.cpp
> +	if ((dmisc10 <= 0 || replay_version_check(0, 37)))
its what we did for ropes but good point

2024-12-09 08:03 UTC, connorjclark commented
Can you include in this PR the changes necessary to inform users that this feature exists? At minimum, the label in the enemy editor needs to be set, via `EnemyEditorDialog::loadEnemyType` I think?

2024-12-09 08:04 UTC, connorjclark commented on src/zc/guys.cpp
> +	if ((dmisc10 <= 0 || replay_version_check(0, 37)))
I confirmed that none of the replays fail w/o this check, so let's remove the replay bump here.

If we come across a quest which utilized misc10 for vires/pols in this way, we can add a compat rule at that time.

2024-12-10 01:17 UTC, connorjclark requested changes
(see my other comments)

2024-12-10 01:24 UTC, connorjclark approved these changes

2024-12-10 01:37 UTC, Jambu2024 commented on src/zc/guys.cpp
> +	if ((dmisc10 <= 0 || replay_version_check(0, 37)))
done

2024-12-10 04:13 UTC, merged